WITH RENTAL_DURATION AS (
    SELECT 
        H.HISTORY_ID,
        C.DAILY_FEE,
        C.CAR_TYPE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 'NONE'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT 
    R.HISTORY_ID,
    ROUND(R.DAILY_FEE * R.DURATION * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM RENTAL_DURATION R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON R.CAR_TYPE = P.CAR_TYPE 
    AND R.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, R.HISTORY_ID DESC;