WITH FRONT_END_SKILL AS (
    SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'
),
DEVELOPER_GRADES AS (
    SELECT 
        CASE 
            WHEN EXISTS (SELECT 1 FROM FRONT_END_SKILL F WHERE (D.SKILL_CODE & F.CODE) > 0)
                 AND (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0 THEN 'A'
            WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0 THEN 'B'
            WHEN EXISTS (SELECT 1 FROM FRONT_END_SKILL F WHERE (D.SKILL_CODE & F.CODE) > 0) THEN 'C'
        END AS GRADE,
        D.ID,
        D.EMAIL
    FROM DEVELOPERS D
)
SELECT GRADE, ID, EMAIL
FROM DEVELOPER_GRADES
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;